# Generated by Django 3.1.7 on 2021-03-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
                ('current_temperature', models.CharField(max_length=30)),
                ('today_min_temperature', models.CharField(max_length=30)),
                ('today_max_temperature', models.CharField(max_length=30)),
                ('this_week_min_temperature', models.CharField(max_length=30)),
                ('this_week_max_temperature', models.CharField(max_length=30)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
